#!/bin/bash

###############################################################################
# Wrapper script - installs kon script from docker image.
###############################################################################
mkdir -p /opt/bin
if [ ! -d /etc/kon ] || [ ! -f /etc/kon/kon.sh ]; then
    mkdir -p /etc/kon
    docker run --rm -v /etc/kon:/etc/kon thenatureofsoftware/kon:v0.3-alpha
fi
source /etc/kon/kon.sh
